### ISSUE TITLE
todos

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/h2a-buses#1]
- [x] static cache of routes? - **Implemented. See #4**
- [x] table to input how many buses of each type per bus line - **Implemented. See #4** 
- [x] live chart of emissions and cost - **Implemented. See #35**
- [x] github pages deployment
- [x] typescript typed deserialise from file - can we cache and hence avoid calling routing machine again and again - **Done and available on the main branch. We store `coordinate`, `totalDistance` and `totalTime` data in `localStorage`**
- [ ] add more buses
- [x] cache the result of routing machine
- [x] deploy
- [ ] general documentation of features
- [ ] document: adding new buses
- [ ] document: populating the cache with route info for new buses
- [x] spread the buses equally when there are multiple buses on a selected route - **Implemented. See #35**
